- docs/initial-configuration.txt
Adds instructions for configuring and caching the time wheel
> Time wheel config docs

- docs/projects-and-packages.txt
Adds update_package command instructions and updates arguments and outputs in the create_package command.
> Adds update_package command instructions

- docs/initial-configuration.txt
- docs/projects-and-packages.txt
Adds documentation regarding package settings
> Documented package settings

- docs/command-line-reference.txt
For #24 a new and improved pull request from a branch based on an up-to-date 4.1.0 branch!
Went and peeked at the code and added a couple undocumented options.
(I'm gonna add a plugin to my editor that stops me from pushing these little whitespace artifacts...)
> added map layer commands and option to command-line-reference.txt

- docs/basic-production-configuration.txt
- docs/index.txt
This here's for #26 
Minor content changes were made, but it's pretty much the same just in pretty RTD format.
I can think of a few content changes/additions I'd like to make, but those can be handled in other issues.
From here, it should be pretty easy to tackle #11
> migrated wiki documentation on production configuration for #26

- docs/command-line-reference.txt
- docs/import-export.txt
For Issue #30 
I think I covered everything; lemme know what you think.
> Documented the import of .relations files for Related Resources

- docs/creating-a-development-environment.txt
This is a small update to address https://github.com/archesproject/arches/issues/3646
> add note about running yarn install during dev

- docs/command-line-reference.txt
- docs/examples/base.py
- docs/examples/boolean.htm
- docs/examples/boolean.js
- docs/examples/date.htm
- docs/examples/date.js
- docs/examples/sample-function.htm
- docs/examples/sample-function.js
- docs/examples/sample-widget.htm
- docs/examples/sample-widget.js
- docs/examples/sample-widget.json
- docs/examples/sample_datatype.py
- docs/examples/sample_function.py
- docs/functions-widgets-datatypes.txt
This is a big PR covering #47 and #48. I went as in-depth as I could and tried to be thorough. A sanity-check of the technical details would be good here, and I'm also open to cosmetic advice.
You can preview the docs here: https://arches-dev.readthedocs.io/en/function_widgets_datatypes/functions-widgets-datatypes.html
> Function widgets datatypes

- docs/command-line-reference.txt
- docs/examples/default-card.htm
- docs/examples/default-card.js
- docs/examples/new-card-component.json
- docs/functions-widgets-datatypes.txt
Add a section to the Functions, Widgets, and Datatypes page regarding the development, configuration, and registration of Card Components
#66 
---
> [66] Document creation and registration of Card Components

- docs/rdm.txt
Formatting fixes; Add information about SKOS file format to RDM documentation
#10 
I thought of adding a section in the developer documentation about the JSON dictionary with the prefLabel UUID's, but it turns out those are totally unnecessary (and I could have saved myself some time when writing the skos_migrator tool by just eliminating them). 
For the purpose of importing into Arches, it's just plain RDFLib -- I looked at the Arches code. Regular plain SKOS in accordance with upstream docs will be fine, and there's not much to say beyond that.
Feedback welcome as usual.
---
> 10 rdm formats

- docs/release-process.txt
> Updates release schedule

- docs/command-line-reference.txt
- docs/import-export.txt
Addresses #77, #3, as well as some general improvements.
---
> 77 improve import export info

- docs/designing-the-database.txt
some updates to the designer documentation based on Farallon feedback.
#69 
---
> 69 new designer docs

- docs/_static/js/main.js
- docs/conf.py
finally got around to implementing click reloading for images to accommodate single play gifs.
#83 
---
> add js to reload images on click events

- docs/_static/css/style.css
- docs/exporting-v3-data.txt
- docs/index.txt
- docs/migrate-hip-app.txt
- docs/migrate-other-app.txt
- docs/v3-to-v4-migration.txt
add the documentation for data migration from v3 to v4.
no ticket created for this effort.
This workflow will be supported in 4.4, so these commits will **not** be cherry-picked into 4.3.3, they will just stay in master (i.e. they'll be in /latest docs until 4.4 is released and then they'll be in /stable as well).
---
> Document v3 v4 workflow

- docs/arches-and-elasticsearch.txt
- docs/command-line-reference.txt
Added sections about re-indexing elasticsearch, and also address the DEBUG = True memory "leak".
#96 
---
> 96 debug false index note

- docs/serving-arches-with-apache.txt
Added the WSGIAuthorization directive needed in the Apache configuration section.
> Adds Apache collector directive information

- docs/arches-and-elasticsearch.txt
- docs/command-line-reference.txt
- docs/requirements-and-dependencies.txt
> update docs for new version of ES, re #137

- docs/api.txt
I've added some documentation here on the GeoJSON API that was missing.  Hopefully this is complete enough to make it useful!
> adds geojson api documentation

- docs/projects-and-packages.txt
adds description of argument `-bulk` for `load_package`
---
> adds documentation for -bulk argument for load_package, re #5487

- docs/index.txt
- docs/setting-up-supervisord-for-celery.txt
Adds a guide to set up supervisord for celery on a linux machine
#153 
> adds documentation to guide setup of supervisord for celery, re #153

- docs/setting-up-supervisord-for-celery.txt
Fixes link markdown in supervisord setup page
#153 
---
> 153 supervisord docs

- docs/setting-up-supervisord-for-celery.txt
edits spacing, fixes type
#153 
---
> edits spacing, fixes type, re #153

- docs/ontologies-in-arches.txt
- docs/projects-and-packages.txt
> Adds documentation on how to load an ontology

- docs/command-line-reference.txt
Updates load ontology command and removes the add tileserver layer command. re archesproject/arches#3693, archesproject/arches#5407
> Updates load ontology command

- docs/examples/sample_datatype.py
- docs/functions-widgets-datatypes.txt
> Adds issearchable property to datatype definition

- docs/requirements-and-dependencies.txt
fix up the link to the current ubuntu installation script.
#164 
---
> add link to ubuntu setup script #164, other small fixes

- docs/designing-the-database.txt
> changes width of map card screenshot, re #176

- docs/designing-the-database.txt
> edits links, adjusts screenshot size #176

- docs/designing-the-database.txt
> fixes link to source_layer, re #176

- docs/command-line-reference.txt
- docs/installation.txt
- docs/requirements-and-dependencies.txt
> 440 reindex es

- docs/task-management.txt
> adds alternate way of launching worker for debug purposes

- docs/functions-widgets-datatypes.txt
- docs/index.txt
- docs/locally-hosting-iiif.txt
> 197 cantaloupe iiif

- docs/managing-and-hosting-iiif.txt
> fix typo, rename file, re #197

- docs/managing-and-hosting-iiif.txt
> fix typos, formatting, clarify intro sentence, re #197

- docs/creating-resources.txt
- docs/deleting-resources.txt
- docs/index.txt
- docs/searching.txt
Moved headings out of Using Arches to Administering; renamed Creating Resources; Added Searching and Deleting Resources
Created new issues to track the addition of new content for new sections.
---
- [X ] the PR branch was originally made from the base branch
> Dev 5.1 Using Arches section merge

- docs/managing-permissions.txt
Added github issue links to Managing Permissions headings
---
- [X ] the PR branch was originally made from the base branch
- [X ] after these changes the docs build locally without error
> added links to git issues

- docs/_static/css/style.css
- docs/arches-in-production.txt
- docs/configuring-arches.txt
- docs/index.txt
- docs/initial-configuration.txt
- docs/installation.txt
- docs/migrating-a-local-app-to-aws-ec2.txt
- docs/projects-and-packages.txt
- docs/requirements-and-dependencies.txt
- docs/v3-to-v4-migration.txt
This is a pretty big overhaul to the way the installation guide is structured.
Objectives for this rewrite:
- make a more clear explanation of virtual environments, but also make it a little more separate from the actual arches installation #111
- condense and redistribute the many different settings/configuration steps (see new section CONFIGURING)
- reduce and clarify overall number of install steps (related to #112)
- make clearer distinction between core arches and project
Progress on other existing tickets:
- make more distinct sections for Projects and Packages (#208, #206)
- updates the load_package command in some places (#214) (but not all, still needs to be updated in CLI Reference)
---
This box **should only** be …
> Dev 5.1 install update

- docs/import-export.txt
> fix typo 128

- docs/serving-arches-with-apache.txt
Overhaul of "Serving Arches with Apache" documentation.
#119, #125, #232
These steps could use testing, but they are vastly better than the outdated content that we had before.
---
> update apache docs, re #119, #125, #232

- docs/accessibility.txt
- docs/index.txt
Added new Accessibility page and menu item under "DEVELOPING WITH ARCHES"
---
> 237 Added new Accessibility page and menu item

- docs/overview.txt
In Overview page, updated the link for the Arches Forum to new Discourse link 
---
> update forum links

- docs/accessibility.txt
- docs/import-export.txt
- docs/index.txt
- docs/overview.txt
- docs/serving-arches-with-apache.txt
In Overview page, updated the Arches Forum link to the new Discourse link.
---
> 5.1 forumupdate

- docs/managing-permissions.txt
add a bit more structure (and internal llinks) to the permissions section
---
> organize permissions section

- docs/creating-resource-reports.txt
> commits first pass at doc on creating custom resource reports, re #205

- .readthedocs.yaml
- docs/serving-arches-with-apache.txt
- requirements.txt
see https://github.com/archesproject/arches-docs/pull/259
---
> 258 fix rtd env inconsistency 5.1

- docs/creating-a-development-environment.txt
- docs/installation.txt
- docs/projects-and-packages.txt
Fixes some old content in the dev environment instructions.
Also adds a good bit of content with regard to upgrading projects and using projects to overwrite core Arches functionality.
#168
#190 
#231
---
> Dev install updates 168

- docs/creating-a-development-environment.txt
- docs/installation.txt
- docs/projects-and-packages.txt
> 6.0 dev env update

- docs/adding-javascript-dependencies.txt
- docs/conf.py
- docs/managing-javascript-dependencies.rst
- requirements.txt
A few small updates.
Adds the ability to use .rst files re #255
Adds guidance on javascript dependencies #61
Fixes regression of #258 
The name of the javascript deps file was changed, so it will not show up in the table of contents until the new file name is reflected (this will come along with a larger set of updates to the TOC).
---
> Master 61 and more

- docs/adding-javascript-dependencies.txt
- docs/conf.py
- docs/managing-javascript-dependencies.rst
- requirements.txt
Merge recent commits to master from PR #270 into the 6.0 (stable) branch.
see #270 
---
no applicable
> 6.0 backport

- docs/localizing-arches.txt
added localization information from 5.1 release notes
Addresses issue #210 partially
---
> adding localization info

- docs/localizing-arches-ag.rst
- docs/localizing-arches.txt
Half completes #279... Add the content from @aarongundel into a new page that is linked from the existing one, at least. Still need to properly combine these pages at a later date.
---
> add localization content from @aarongundel; still must be combined #279

- docs/arches-collector-checklist.txt
- docs/conf.py
- docs/designing-the-database.txt
- docs/extensions/workflows.rst
- docs/managing-and-hosting-iiif.txt
- docs/managing-permissions.txt
- docs/projects-and-packages.txt
- docs/settings-beyond-the-ui.txt
> Master 117 244 262

- docs/designing-the-database.txt
- docs/import-export.txt
Cherry-picking the two commits in this PR into master branch: https://github.com/archesproject/arches-docs/pull/290
> Cherry pick to master PR 290

- docs/import-export.txt
Update resource-instance(-list) import format
---
> updated resource-instance node import

- docs/settings-beyond-the-ui.txt
adds documentation for using EXTERNAL_OAUTH_CONFIGURATION setting to authenticate users via SSO.
This feature will be included in the 7.3.0 release at the end of January 2023
---
> adds documentation for external oauth config

- docs/deployment/arches-in-production.txt
- docs/installing/requirements-and-dependencies.txt
Updates installation requirements information to note memory requirements for production builds (frontend assets).
Hopefully spares heartache and despair in diagnosing why production frontend builds fail
---
> Update production memory needs for 274 pydata theme

- docs/conf.py
- docs/robots.txt
This merges cherry picked commits with robots.txt related additions.
[](https://github.com/archesproject/arches-docs/issues/297)
We already merged these commits into Master
---
- [ x] the PR branch was originally made from the base branch
- [ x] after these changes the docs build locally without error
- [x ] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged
> 7 3 robots merge into 7.3

- docs/deployment/serving-arches-with-apache.txt
Added Apache WSGI config.
Sorry about the big diff. My VSCode does lots of "helpful" formatting cleanup.
(https://github.com/archesproject/arches-docs/issues/309)
I'll make the corresponding changes to the other branches for other releases, but they won't be a cherry-pick because of the new file organization
---
> Added Apache WSGI config

- docs/using-aws-s3.txt
I updated the S3 example to reference the current version of the Python Boto3 library for interfacing with S3.
I also made a few edits to discuss other cloud storage providers so it doesn't read quite like an AWS advertisement. Please let me know if you think these changes properly reflect the current reality.
(https://github.com/archesproject/arches-docs/issues/323)
This change will need to applied to almost all branches.
---
> Updated s3 directions, noted other cloud providers,  added warning

- docs/deployment/using-aws-s3.txt
> Reimplemented s3 and other cloud storage updates from 7.3 branch

- docs/deployment/setting-up-supervisord-for-celery.txt
Re-implemented change about celery and supervisor documentation from an already approved PR into the new main branch.
No need for a PR review, this change was already approved.
> Re-implemented celery updates merged into 7.3 branch

- docs/examples/quick-resource-create-workflow.js
- docs/extensions/workflows.rst
Update example javascript code for defining/registering custom workflows so they work with V7 Arches expectations
https://github.com/archesproject/arches-docs/issues/328
@chiatt approved in a comment to the ticket.
---
> Updated workflow functions

- docs/deployment/index.rst
- docs/deployment/serving-arches-with-apache-nginx.txt
Minor update on the Apache + Ngnix documentation to respond to @mradamcox suggestions
https://github.com/archesproject/arches-docs/issues/267#issuecomment-1505560690
---
> Improved Apache Nginx clarity

- docs/index.rst
Updates landing page for new documentation template
None
This will be the basis for the next v7.4.0 release documentation branch
---
> main <- new intro branch

- docs/administering/bulk-data-manager.txt
Adds a brief overview of the Edit functions in the Bulk Data Manager
7.4 release notes
Works in testing here: https://arches.readthedocs.io/en/bulk_update2_7_4/administering/bulk-data-manager/
---
> Bulk update2 7 4

- .readthedocs.yaml
Meet new read the  docs requirements
See: https://blog.readthedocs.com/migrate-configuration-v2/
---
> Update read the docs build

- docs/conf.py
Fixes bug where read the docs env variable is no longer read
Fixes build errors.
---
> Attempt to fix html_theme glitch

- docs/deployment/migrating-a-local-app-to-aws-ec2.txt
Updates AWS deployment documentation to discuss networking and security groups.
Provides additional information about how to use security groups to grant the minimal needed permissions between different nodes in a distributed architecture. Also discusses some useful settings.
We may want to add more information about connecting to RDS instances in future updates
---
> Added more info on security, RDS, and ALLOWED_HOST configs

- docs/installing/installation.txt
Virtual env needs activation for yarn build
[Virtual env needs activation for yarn build](https://github.com/archesproject/arches-docs/issues/375)
Will add this to all 7.x documentation branches.
---
> 7.4 <- Env 7 4

- docs/developing/reference/command-line-reference.txt
> Fix broken link in CLI reference

- docs/developing/extending/creating-extensions.rst
- docs/developing/getting-started/customization-considerations.rst
- docs/developing/index.rst
Added high-level guidance for making customizations. Will need to coordinate with the dev team about what customization pathways are best for different scenarios.
None, but we needed to provide some discussion about maintainability in customizing Arches.
TODO: Add more specifics about to make choices across different kinds of customizations (cards, widgets, extensions, apps..)
Updates can be temporarily read here: https://arches.readthedocs.io/en/dev_m/developing/getting-started/customization-considerations/
---
> Added high-level guidance for making customizations

- docs/configuring/settings-beyond-the-ui.rst
- docs/developing/advanced/accessibility.rst
Added instructions for activating the accessibility mode.
No issue. However this is a major enhancement for v 7.5
---
> Added accessibility mode discussion and cross-ref

- docs/deployment/implementing-ssl.rst
- docs/deployment/serving-arches-with-apache-nginx.rst
- docs/developing/getting-started/creating-a-development-environment.rst
- docs/installing/installation.rst
- docs/installing/requirements-and-dependencies.rst
Time marches on. 7.6 will require python 3.10 as min.
Refs archesproject/arches#10456
> Update docs to suggest at least python 3.10

- docs/developing/extending/extensions/etl-modules.rst
Add the section about the etl module
- register/unregister the etl module
---
> Add etl module section

- docs/index.rst
Added an annotated table of contents to the landing page to guide navigation
We got some feedback that we lacked installation instructions, which suggests that it was too hard to find installation instructions.
We will need to make some additional improvements to the navigation / usability of the documentation after we get more specific feedback about the nature of the issues/problems.
See the update temporarily deployed here: https://arches.readthedocs.io/en/toc_7_5/
---
> 7.5 <- Toc 7 5

- docs/developing/advanced/accessibility.rst
Typo fixes for accessibility development tips
> Copy edit accessibility docs

- docs/administering/bulk-data-manager.rst
Adds some tips about task / worker management for the bulk data manager. 
In response to this forum discussion: https://community.archesproject.org/t/stuck-tasks-in-7-5-0-bulk-data-manager/2217/8
---
> Added SQL to delete stuck tasks

- docs/administering/designing-the-database.rst
- docs/developing/reference/import-export.rst
These are simple typo fixes -- the diff pretty much says it all.
--
(I confess I did not actually test the build after making these changes.  If these tiny edits break the build, I would be astonished!)
> Fix a few typos

- docs/installing/projects-and-packages.rst
---
- [x ] the PR branch was originally made from the base branch
> Add link to update a package in cases of major version upgrades

- docs/developing/vue/arches-vue-integration.md
> adds documentation around Vue testing

- docs/developing/getting-started/creating-a-development-environment.rst
Add instructions corresponding to archesproject/arches#10575
---
> Update dev environment block with pre-commit

- docs/deployment/using-aws-s3.rst
- docs/developing/getting-started/creating-a-development-environment.rst
- docs/developing/reference/command-line-reference.rst
Partner to archesproject/arches#11113
> Replace references to requirements.txt

- docs/developing/extending/extensions/functions.rst
Updates to docs about creating custom functions
(https://github.com/archesproject/arches-docs/issues/441)
I haven't actually designed any functions, so I'll need some guidance to make sure this is correct.
To see the updates:
1. Function hooks: https://arches.readthedocs.io/en/funcs_7_5/developing/extending/extensions/functions/#function-hooks
2. Function descriptions:  https://arches.readthedocs.io/en/funcs_7_5/developing/extending/extensions/functions/#defining-the-function-s-details
---
> Made suggested updates to functions docs

- docs/administering/security.rst
- docs/deployment/arches-in-production.rst
Added command to check security settings suggested by @jacobtylerwalls 
https://github.com/archesproject/arches-docs/issues/458
---
> Added command to check security settings

- docs/developing/reference/command-line-reference.rst
- docs/installing/installation.rst
- docs/installing/projects-and-packages.rst
See archesproject/arches#11497
Fixes #434
(Please wait to merge until archesproject/arches#11497 is merged.)
> Replace `arches-project create` command

- docs/deployment/arches-in-production.rst
Added more discussion about the `CSRF_TRUSTED_ORIGINS` and added discussion of `SECURE_PROXY_SSL_HEADER`.
[](https://github.com/archesproject/arches-docs/issues/462)
---
> Added CSRF and SECURE_PROXY_SSL_HEADER setting

- docs/deployment/implementing-ssl.rst
- docs/deployment/serving-arches-with-apache-nginx.rst
- docs/developing/getting-started/creating-a-development-environment.rst
- docs/installing/installation.rst
- docs/installing/requirements-and-dependencies.rst
Arches 8.0 requires Python 3.11+
Refs archesproject/arches#11380
> Bump minimum python version to 3.11

- docs/developing/reference/command-line-reference.rst
I've added a brief description of the csv output files from export_business_data and what they include. 
#467
---
> Adds additional information about the outputs from the export_business_data function for csv.

- docs/developing/reference/api.rst
Update oauth settings name from the deprecated name
---
> Update oauth settings name

- docs/deployment/arches-in-production.rst
- docs/user-guide/index.rst
- docs/user-guide/updating-resources.rst
> Formatting fixes

- docs/developing/reference/import-export.rst
Added some tips for using the SQL relational views based on RASColl experience.
None
May need update in the future as issues with the relational views get fixed.
---
> 7.6 <- Sql 7 6

- docs/administering/designing-the-database.rst
Add information on non-localized-string datatype to the list of core Arches datatypes
#486 
---
> Add line for non-localised-string, plus specify string is for localised

- docs/deployment/implementing-ssl.rst
- docs/deployment/serving-arches-with-apache-nginx.rst
Adding export deliverables to the Apache configuration.
#496 
Nginx isn't something I've used, so I may need some input on if anything needs adding to the example in the docs @aarongundel @ekansa 
---
> Add export deliverables to apache config
