docs/command-line-reference.txt

I've migrated the Import commands from the wiki Command Line Reference page.
Let me know if I'm off base on anything. One bit of ambiguous wording I noticed:
> ow - this option determines how resources with duplicate ResourceIDs will be handled. This option only applies to csv import. json import overwrites data. It will not modify existing data within a card or node.
What does "it" refer to? JSON import, or the -ow option?
Thanks!

Docfix 4.1.0 cli reference

---

docs/api.txt

Added the API calls for the Activity Stream API. This allows an authenticated client to access a machine-readable form of the edit log, and know which resources have been created, updated, or deleted.
This is linked to Issue/PR archesproject/arches#4938 
---
(tested via `make`ing the singlehtml version.)

Activity Stream API reference added

---

docs/exporting-v3-data.txt
docs/migrate-hip-app.txt
docs/migrate-other-app.txt
docs/v3-to-v4-migration.txt

Much work was undertaken to improve the v3 v4 data migration coming out of the Historic Places LA upgrade project. These docs updates reflect the improvements which are currently in the `stable/4.4.x` branch of core Arches (https://github.com/archesproject/arches/pull/5050) as well as the `master` branch (https://github.com/archesproject/arches/pull/5091).
#122 (as well as other work not previously written up as an Issue)
---

Master update v3v4 workflow

---

docs/requirements-and-dependencies.txt

updates the following software dependencies for arches version 5 release:
Python 2.7 --> 3.7
PostgreSQL 9.6 --> 12
PostGIS 2 --> 3
Elastic Search 7 --> 7.4
Mapnik has been removed as a software dependency.
https://github.com/archesproject/arches/issues/5567
---

5567 update software dependencies

---

docs/requirements-and-dependencies.txt

addresses issues described both in #164 and here: https://github.com/archesproject/arches/issues/5731
fixes a link
#164 

update link to point to correct version of the linux install script, re: 164

---

docs/requirements-and-dependencies.txt

We've found that GDAL 3 is not supported in Django 1.11. However, that is the GDAL version that the current OSGEO4W installer currently installs, so our documentation was directing people to download an incompatible version of GDAL. This fixes that by directing them to a different installation tutorial that supports the installation of older releases.
#152 
this fix is only applied to the 4.4.3 branch (stable) as we don't anticipate this to be a problem with Arches 5 that uses Django 2.
---

direct installation of GDAL 2.x and link to UCLA tutorial (thanks!!) #152

---

.gitignore
docs/creating-new-map-layers.txt
docs/creating-resources.txt
docs/requirements-and-dependencies.txt

Removes tileserver command documentation and warns users that the generic resource relationship pattern will be deprecated in favor of using the resource-instance datatype. re #162

Warns users of generic relationship deprecation

---

.readthedocs.yaml
requirements.txt

introduces .readthedocs.yaml file to make more consistent environments. Also pins sphinx_rtd_theme to >= 0.5.2.
#258 
---

258 fix rtd env inconsistency

---

docs/managing-and-hosting-iiif.txt

This PR updates the IIIF and Cantaloupe documentation to reflect more detailed implementation concerns on the backend (setting up Cantaloupe) as well as the current/updated state of how IIIF Manifests get created, namely via the Image Service Manager which until now was not documented.
#280 
---

updates IIIF/Cantaloupe setup for backend and frontend, re #280

---

docs/designing-the-database.txt
docs/import-export.txt

Adds a good deal of information about resource import vis a vis datatype formats. Also added a section in the Designing the Database area listing core Arches default data types (content generally taken from the existing in-app help).
#76 
#127 
#243 
#289 
---

6.1 datatype updates 76 etc

---

.gitignore
docs/conf.py
docs/robots.txt

1. Added to gitignore to keep pyenv related files out of version control
2. Added a robots.txt file and config
1. Ergonomics to keep pipfile and pipfile.lock files for developers using pyenv
2. Need for a robots.txt file to direct search engine indexing to current documentation  https://github.com/archesproject/arches-docs/issues/297
I ran a build on ReadTheDocs to make sure that this actually works. I also checked the validity of the robots.txt directives using https://technicalseo.com/tools/robots-txt/
We should add the robots.txt file and updates conf.py commit to other release branches via cherry-pick
---

PR Merge branch Pipfile ignore into Master

---

docs/developing/reference/import-export.txt

Updates description of the edtf datatype, level 2 support, and notes a bug and workaround for certain kinds of string values used with this datatype.
(https://github.com/archesproject/arches-docs/issues/298)
Thanks @mradamcox for describing exactly the documentation changes required.
---

Added EDTF level support and bug workaround

---

docs/import-export.txt

Adds documentation about SQL ETL instance performance issue for node-instance inserts when Postgres/PostGIS is installed on an Ubuntu, Debian, and Alpine OS. Adds the workaround provided by @robgaston and estimate of when the fix will be part of a future Arches release
References this documentation issue: https://github.com/archesproject/arches-docs/issues/311
References this discussion: https://github.com/archesproject/arches/issues/9049
I think this mainly impacts Arches v7x releases. I will cherry-pick these commits to the other v7x documentation branches after approval of the PR.
---

Added SQL ETL OS bug note and workaround

---

docs/arches-collector-checklist.txt
docs/arches-collector-manager.txt
docs/using-arches-collector.txt

Added Collector deprecation warning to v6 version branch
(https://github.com/archesproject/arches-docs/issues/284)
Discussed this with the GCI Arches team. The plan is to add this deprecation warning to the v6 branches, and remove all reference to Collector from v7 branches.
---

Added collector deprecation warning

---

docs/administering/managing-permissions.txt
docs/deployment/serving-arches-with-apache.txt
docs/developing/reference/api.txt
docs/introduction/overview.txt

Removed reference (except for a historical note) about Collector. The GCI Arches team requested this to avoid confusion about the status of Collector.
(https://github.com/archesproject/arches-docs/issues/284)
The v6 branches have a deprecation warning, the v7 branches (and with this PR the master branch) will have all reference to Collector purged.
---

Removed references to the deprecated Collector

---

docs/requirements-and-dependencies.txt

There has been some forum discussion and an issue raised here about Node.js and Yarn dependencies. I consulted with @chiatt about this and he provided information about compatibility issues and recommended installation approaches.
(https://github.com/archesproject/arches-docs/issues/275)
We will revisit this with future versions of Arches that may use the npm package manager and / or more recent versions of yarn.
---

Updated Node and Yarn dependency and installation docs

---

docs/installing/requirements-and-dependencies.txt

Implement similar change to master branch for PR already accepted for 7.3 branch, in response to this issue: (https://github.com/archesproject/arches-docs/issues/275)
(https://github.com/archesproject/arches-docs/issues/275)
The edit here saw extensive discussion and reflects the current consensus about how to best explain navigating Node.js and Yarn dependencies. It also has a minor clarification on PostresSQL version expectations. 
Should a similar update be made for the v6.2 documentation? I'm less familiar with v6x requirements.
---

Update Node and Yarn dependency + install guide

---

docs/api.txt

Updated API documentation to note that the default JSON-LD format representations will fail if no ontology is in use.
(https://github.com/archesproject/arches-docs/issues/319)
I'm not sure exactly where to put this new advice. It seems to be OK here, but I'm open to suggestions:
https://arches.readthedocs.io/en/api_json_7_3/api/#general-expectations-requesting-json-ld
---

Api json 7 3

---

docs/creating-a-development-environment.txt

Updates a css path for the Overwriting Core Arches Content section
(https://github.com/archesproject/arches-docs/issues/321)
@ydrea  Is there anything else we should update here? Is there any impact on behaviors with "collectstatic" etc?
---

Updated css path

---

docs/setting-up-supervisord-for-celery.txt

This updates supervisord and celery documentation to explain more about when they may be required, provide some options for using Redis, and document a workaround for some config syntax that needs updating. It also includes some of admin commands suggested by @mradamcox.
Demo here: https://arches.readthedocs.io/en/celery_7_3/setting-up-supervisord-for-celery/
(https://github.com/archesproject/arches-docs/issues/310)
ReadTheDocs temporarily relaxed PDF documentation build checking, so I'd like to get this in ASAP before they make builds harder again.
I'll be adding some more production config documentation about Nginx and Docker also.
---
This box **should only** be checked you intend to follow through on it (we can do it on our …

Celery 7 3

---

docs/deployment/serving-arches-with-apache.txt

This provides some instruction on using Gunicorn and Nginx, with an example Nginx config that describes how to compress css, javascript, etc.
https://github.com/archesproject/arches-docs/issues/267
I am using more or less the same Nginx config in my Docker deployed Arches instance, so It seems to work. I'm not an Nginx guru, so I'm sure it could be better, but it's nice to provide a working starting point for people wanting to deploy Arches with Nginx.
You can view the update here;
https://arches.readthedocs.io/en/nginx_m/deployment/serving-arches-with-apache/#configure-nginx
---

Added Nginx to serving arches, with config

---

docs/_templates/footer.html
docs/conf.py

Reimplements the CC-BY-SA license merged into the main branch. This has a slightly different implementation style suitable for the older Sphinx template. 
None.
See: https://github.com/archesproject/arches-docs/pull/340
---

Extended footer template to include CC-BY-SA license

---

docs/_templates/footer.html
docs/conf.py
docs/localizing-arches.txt

Responds to a gap in documentation identified by @chiatt where we lacked instruction on how to structure CSV files to import business data that contain string nodes in multiple languages.
https://github.com/archesproject/arches/issues/9288#issuecomment-1513028942
The updated section is demoed here: https://arches.readthedocs.io/en/csv_int_7_3/localizing-arches/#csv-column-field-names-indicating-languages
Once approved, I'll update all version 7 branches to include this update.
---

Added subsection for multiple language CSV column names

---

docs/user-guide/searching.txt

Updates the user guide for search to discuss escaping characters used as search operators
Adds documentation to the updates made with this PR: https://github.com/archesproject/arches/pull/9574
The updated documentation can be (temporarily) reviewed here:  https://arches.readthedocs.io/en/search_7_4/user-guide/searching/#escaping-search-operator-characters
---

Search 7 4

---

docs/administering/managing-permissions.txt

Added description of the **Resource Exporter** group and how it use this group to control search result resource instance data exports.
Version 7.4.0 release notes.
Temporarily demonstrated here: https://arches.readthedocs.io/en/export_perms_7_4/administering/managing-permissions/#managing-users-and-groups-in-django-admin
---

Added resource exporter

---

docs/developing/advanced/task-management.txt

Add a workaround for developers on apple silicon macs to be able to launch celery.
Closes #362

Describe celery workaround on Apple Silicon (M1) Macs

---

docs/developing/reference/api.txt

Adds the requirement for the graph to be identified when making a PUT request for creating or updating a resource. 
Relates to https://github.com/archesproject/arches/issues/9968
---

Added requirement for graph identification in resource PUT

---

docs/deployment/using-aws-s3.txt

`DEFAULT_FILE_STORAGE` was deprecated in Django 4.2, which is used in Arches 7.5. Update the docs to avoid suggesting the use of a deprecated setting.
See:
https://docs.djangoproject.com/en/4.2/releases/4.2/#custom-file-storages
(This should only get cherry-picked to 7.5)

Update example for Django 4.2 storage settings

---

docs/deployment/using-aws-s3.txt

@aarongundel alerted me to the fact that I missed the "BACKEND" key.
[Reference](https://docs.djangoproject.com/en/4.2/ref/settings/#storages)
Follow-up to #367

Fix STORAGES example

---

docs/deployment/setting-up-supervisord-for-celery.txt

@mradamcox  pointed out a potential cron issue with starting supervisor
[](https://community.archesproject.org/t/startup-supervisor-celery-on-reboot/2115)
Hopefully this helps make supervisor/celery (which has been a vexing pain) more maintainable. 
---

Add Adam Cox advice on Supervisor and Cron

---

docs/administering/designing-the-database.txt
docs/developing/extending/extensions/card-components.rst

Card types documentation is hard to find, making so it appeared this card lacked explanation. 
[Documentation already existed but was hard to find](https://github.com/archesproject/arches-docs/issues/355)
We probably need to do LOTS more to add cross references and guides for how to find useful info
---

7.4 <-cross references to card types

---

docs/developing/extending/extensions/functions.rst
docs/developing/extending/extensions/resource-reports.rst
docs/developing/extending/extensions/workflows.rst
docs/examples/boolean.js
docs/examples/date.js
docs/examples/default-card.js
docs/examples/quick-resource-create-workflow.js
docs/examples/sample-function.js
docs/examples/sample-plugin.js
docs/examples/sample-widget.js

In 7.0, the pattern for registering custom components changed slightly. See:
https://github.com/archesproject/arches/blob/77dcfef2322967163551b27dd34e4dbbd316e2ef/releases/7.0.0.md?plain=1#L176-L206

Update example custom components for 7.x

---

docs/deployment/arches-in-production.rst
docs/deployment/migrating-a-local-app-to-aws-ec2.rst

Added discussion of ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS requirements for deploying Arches.
Forum topic: https://community.archesproject.org/t/csrf-verification-failed-error-on-user-login/2225/4
Tested in Read the docs.
---

7.5 <- Csrf 7 5

---

docs/developing/vue/arches-vue-integration.md

393 cbyrd vue component guidance

---

docs/developing/vue/arches-vue-integration.md

In archesproject/arches#10626 we reenabled the eslint rule forbidding `this` in vue templates, so this PR removes the previous advice to use it.
As described in that PR, we weren't getting meaningful type-checking in the templates. Some of the tooling may not be working with our highly custom webpack setup just yet.
~- [ ] after these changes the docs build locally without error~ errors in unrelated files

Remove advice to use `this` in vue templates

---

docs/installing/installation.rst
docs/installing/requirements-and-dependencies.rst

Updates macOS dependency path related instructions.
https://github.com/archesproject/arches-docs/issues/409
https://github.com/archesproject/arches-docs/issues/410
See changes previewed here:
https://arches.readthedocs.io/en/mac_7_5/installing/requirements-and-dependencies/
and
https://arches.readthedocs.io/en/mac_7_5/installing/installation/
---

Added macOS path instructions (issue #410)

---

docs/deployment/setting-up-supervisord-for-celery.rst

update note abot restarting supervisord on reboot, see forum post for more context: https://community.archesproject.org/t/startup-supervisor-celery-on-reboot/2115/4
---

update note about restarting supervisord on reboot

---

docs/developing/reference/command-line-reference.rst

Accounts for a new management command added in https://github.com/archesproject/arches/pull/10837
---

Add edit log managment command

---

docs/developing/extending/creating-new-map-layers.rst
docs/developing/reference/command-line-reference.rst

Added documentation for management command to delete mapbox layers. Improved cross-referencing on discussions of MapBox layer additions and removal
https://github.com/archesproject/arches-docs/issues/416
---

Added command to delete mapbox layer

---

docs/developing/extending/creating-apps.rst

7.6.0 includes subdomain routing for Arches applications. This updates the documentation
---

adds subdomain routing documentation

---

docs/deployment/arches-in-production.rst
docs/developing/extending/creating-extensions.rst
docs/developing/getting-started/creating-a-development-environment.rst
docs/developing/vue/arches-vue-integration.md
docs/installing/installation.rst
docs/installing/requirements-and-dependencies.rst

Replace references to yarn, which is removed in 7.6

Replace references to yarn

---

docs/configuring/settings-beyond-the-ui.rst
docs/examples/arches/function.py
docs/examples/sample_datatype.py

Document the three modes for file type checking, see https://github.com/archesproject/arches/pull/10863.

Document FILE_TYPE_CHECKING setting

---

docs/developing/reference/command-line-reference.rst

Fix error where the CLI documentation incorrectly said multiple graph IDs were allowed in a mapping file
[](https://github.com/archesproject/arches-docs/issues/444)
---

Fixed CLI docs for mapping file, only 1 graph UUID allowed

---

docs/developing/extending/creating-apps.rst

Catch up with changes from archesproject/arches#11016 that removed the `ARCHES_APPLICATIONS` setting.

Update arches applications example

---

docs/deployment/arches-in-production.rst
docs/deployment/migrating-a-local-app-to-aws-ec2.rst

[7.6] Avoid characterizing CSRF_TRUSTED_ORIGINS as a new setting

---

docs/deployment/migrating-a-local-app-to-aws-ec2.rst

Refs archesproject/arches#11231
7.6 only -- this operation no longer does anything.

Remove reference to `-o install`

---

docs/deployment/arches-in-production.rst

We didn't have explicit guidance around this setting before, but it was warned about by `manage.py check --deploy path.to.production.settings`, which we recently added to the upgrade instructions in 7.6.0.md for extra visibility, even though we also link to the the django deployment checklist here in this document, which advises the same action).
Do we want to describe the other action items that users are likely going to need to care about after they see the output of `manage.py check --deploy`?

Add SESSION_COOKIE_SECURE to production docs

---

docs/developing/reference/command-line-reference.rst
docs/installing/installation.rst

We have updated the [behavior of startproject](https://github.com/archesproject/arches/pull/12059) regarding creating a project directory and [nudging implementers towards](https://github.com/archesproject/arches/issues/12028) python package naming conventions.
---

Add context for startproject arguments

---

docs/administering/designing-the-database.rst

Added an animation and explanation on how to activate the Permissions tab in v8. See the update tested here: https://arches.readthedocs.io/en/perm_v8/administering/designing-the-database/#permissions-tab
I also eliminated the obsolete graph visualization that is no longer supported in Arches designer.
https://github.com/archesproject/arches-docs/issues/485
https://github.com/archesproject/arches-docs/issues/487
Yes, v8 graph publishing workflows seem to require a bit update of documentation. But this is a useful first step.
---

Update illustration of permissions UI in v8
